vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        avatars:
            uri_prefix: /divers/images/users
            upload_destination: '%kernel.project_dir%/divers/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
